Repository kubesphere/helm-charts, pull requests merged in 2020-08, with the labels that each got.

#73 Upgrade porter to 0.1.2
  src/test/porter/Chart.yaml
  src/test/porter/README.md
  src/test/porter/crds/bgpconfcrd.yaml
  src/test/porter/crds/bgppeer.yaml
  src/test/porter/crds/eipcrd.yaml
  src/test/porter/templates/NOTES.txt
  src/test/porter/templates/_helper.tpl
  src/test/porter/templates/clusterrole.yaml
  src/test/porter/templates/clusterrolebinding.yaml
  src/test/porter/templates/daemonset.yaml
  src/test/porter/templates/deployment.yaml
  src/test/porter/templates/namespace.yaml
  src/test/porter/templates/role.yaml
  src/test/porter/templates/rolebinding.yaml
  src/test/porter/templates/serviceaccount.yaml
  src/test/porter/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#77 etcd-0.1.0: initial commit for standalone etcd
  src/test/etcd/.helmignore
  src/test/etcd/Chart.yaml
  src/test/etcd/README.md
  src/test/etcd/templates/NOTES.txt
  src/test/etcd/templates/_helpers.tpl
  src/test/etcd/templates/cm.yaml
  src/test/etcd/templates/service.yaml
  src/test/etcd/templates/statefulset.yaml
  src/test/etcd/templates/tests/test-connection.yaml
  src/test/etcd/values.schema.json
  src/test/etcd/values.yaml
Labels: approved, dco-signoff: yes, size/L

#80 postgresql-0.3.1: fix test job issue
  src/test/postgresql/Chart.yaml
  src/test/postgresql/templates/tests/test-connection.yaml
Labels: approved, dco-signoff: no, size/XS

#81 redis-0.3.1: fix test job issue
  src/test/redis/Chart.yaml
  src/test/redis/templates/tests/test-connection.yaml
Labels: approved, dco-signoff: no, size/XS

#83 nginx-1.3.1: empty helm test job by default
  src/main/nginx/Chart.yaml
  src/main/nginx/templates/tests/test-connection.yaml
  src/main/nginx/values.yaml
Labels: approved, dco-signoff: yes, size/XS

#84 etcd-0.1.1: empty helm test job by default
  src/test/etcd/Chart.yaml
  src/test/etcd/templates/tests/test-connection.yaml
  src/test/etcd/values.yaml
Labels: approved, dco-signoff: yes, size/XS

#85 postgresql-0.3.2: empty helm test job by default
  src/test/postgresql/Chart.yaml
  src/test/postgresql/templates/tests/test-connection.yaml
  src/test/postgresql/values.yaml
Labels: approved, dco-signoff: yes, size/XS

#86 redis-0.3.2: empty helm test job by default
  src/test/redis/Chart.yaml
  src/test/redis/templates/tests/test-connection.yaml
  src/test/redis/values.yaml
Labels: approved, dco-signoff: yes, size/XS

#88 nginx-1.3.2: fix ingress issue
  src/main/nginx/Chart.yaml
  src/main/nginx/templates/deployment.yaml
  src/main/nginx/values.yaml
Labels: approved, dco-signoff: yes, size/M

#87 Modify porter description
  src/test/porter/Chart.yaml
Labels: dco-signoff: no, lgtm, size/XS

#89 upgrade Helm to 3.3.0
  build.sh
Labels: approved, dco-signoff: yes, size/XS

#90 minio-6.0.4: upgrade
  src/main/minio/.helmignore
  src/main/minio/Chart.yaml
  src/main/minio/OWNERS
  src/main/minio/README.md
  src/main/minio/templates/_helper_create_bucket.txt
  src/main/minio/templates/_helpers.tpl
  src/main/minio/templates/deployment.yaml
  src/main/minio/templates/post-install-create-bucket-job.yaml
  src/main/minio/templates/post-install-prometheus-metrics-job.yaml
  src/main/minio/templates/post-install-prometheus-metrics-rolebinding.yaml
  src/main/minio/templates/serviceaccount.yaml
  src/main/minio/templates/servicemonitor.yaml
  src/main/minio/templates/statefulset.yaml
  src/main/minio/values.yaml
Labels: approved, dco-signoff: yes, size/L

#91 Feat: Automatically calculates volume type based on instance type
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/README.md
  src/test/csi-qingcloud/templates/sc.yaml
  src/test/csi-qingcloud/values.yaml
Labels: dco-signoff: yes, size/M

#93 downgrade helm from 3.3.0 to 3.2.4 due to helm issue helm/helm#8621
  build.sh
Labels: approved, dco-signoff: yes, size/XS

#94 fix sc.type of qingcloud-csi
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/README.md
  src/test/csi-qingcloud/templates/sc.yaml
  src/test/csi-qingcloud/values.yaml
Labels: dco-signoff: no, size/XS

#97 Update porter version
  src/test/porter/Chart.yaml
  src/test/porter/README.md
  src/test/porter/templates/daemonset.yaml
  src/test/porter/templates/deployment.yaml
  src/test/porter/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#98 rbd
  src/test/rbd-provisioner/.helmignore
  src/test/rbd-provisioner/Chart.yaml
  src/test/rbd-provisioner/README.md
  src/test/rbd-provisioner/templates/clusterrole.yaml
  src/test/rbd-provisioner/templates/clusterrolebinding.yaml
  src/test/rbd-provisioner/templates/deployment.yaml
  src/test/rbd-provisioner/templates/role.yaml
  src/test/rbd-provisioner/templates/rolebinding.yaml
  src/test/rbd-provisioner/templates/serviceaccount.yaml
  src/test/rbd-provisioner/templates/storageclass.yaml
  src/test/rbd-provisioner/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#99 fix rbd provisioner
  src/test/rbd-provisioner/Chart.yaml
  src/test/rbd-provisioner/README.md
  src/test/rbd-provisioner/templates/storageclass.yaml
  src/test/rbd-provisioner/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
