Repository kubesphere/helm-charts, pull requests merged in 2020-07, with the labels that each got.

#55 porter
  src/test/porter/Chart.yaml
  src/test/porter/README.md
  src/test/porter/crds/bgpconfcrd.yaml
  src/test/porter/crds/bgppeer.yaml
  src/test/porter/crds/eipcrd.yaml
  src/test/porter/templates/NOTES.txt
  src/test/porter/templates/_helper.tpl
  src/test/porter/templates/clusterrole.yaml
  src/test/porter/templates/clusterrolebinding.yaml
  src/test/porter/templates/daemonset.yaml
  src/test/porter/templates/deployment.yaml
  src/test/porter/templates/namespace.yaml
  src/test/porter/templates/role.yaml
  src/test/porter/templates/rolebinding.yaml
  src/test/porter/values.yaml
Labels: approved, do-not-merge/invalid-owners-file, lgtm, size/XL

#61 add values.schema.json for redis
  src/test/redis/Chart.yaml
  src/test/redis/values.schema.json
  src/test/redis/values.yaml
Labels: approved, size/M

#62 helm charts for snapshot-controller
  src/test/snapshot-controller/.helmignore
  src/test/snapshot-controller/Chart.yaml
  src/test/snapshot-controller/README.md
  src/test/snapshot-controller/templates/rbac-snapshot-controller.yaml
  src/test/snapshot-controller/templates/setup-snapshot-controller.yaml
  src/test/snapshot-controller/values.yaml
Labels: approved, lgtm, size/L

#63 Update/validation
  src/main/nginx/Chart.yaml
  src/main/nginx/values.schema.json
  src/test/mongodb/Chart.yaml
  src/test/mongodb/values.schema.json
  src/test/postgresql/Chart.yaml
  src/test/postgresql/values.schema.json
  src/test/rabbitmq/Chart.yaml
  src/test/rabbitmq/values.schema.json
Labels: approved, size/L

#64 modify parameters of storage class
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/README.md
  src/test/csi-qingcloud/templates/sc.yaml
  src/test/csi-qingcloud/values.yaml
  src/test/snapshot-controller/README.md
Labels: approved, lgtm, size/S

#65 fix csi-qingcloud expand and snapshot failed
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/README.md
  src/test/csi-qingcloud/templates/node-ds.yaml
  src/test/csi-qingcloud/values.yaml
Labels: approved, dco-signoff: no, lgtm, size/S
