Repository kubesphere/helm-charts, pull requests merged in 2020-09, with the labels that each got.

#100 csi-neonsan: qbd run in container
  src/test/csi-neonsan/Chart.yaml
  src/test/csi-neonsan/README.md
  src/test/csi-neonsan/templates/controller-deploy.yaml
  src/test/csi-neonsan/templates/controller-rbac.yaml
  src/test/csi-neonsan/templates/csi-driver.yaml
  src/test/csi-neonsan/templates/node-ds.yaml
  src/test/csi-neonsan/templates/node-rbac.yaml
  src/test/csi-neonsan/templates/sc.yaml
  src/test/csi-neonsan/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/L

#101 csi-qingcloud-1.2.5: update csi version
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/OWNERS
  src/test/csi-qingcloud/templates/_helpers.tpl
  src/test/csi-qingcloud/templates/config.yaml
  src/test/csi-qingcloud/templates/controller-deploy.yaml
  src/test/csi-qingcloud/templates/node-ds.yaml
  src/test/csi-qingcloud/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/M

#102 csi-qingcloud-1.2.6: fix csi registrar version
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/README.md
  src/test/csi-qingcloud/templates/_helpers.tpl
  src/test/csi-qingcloud/templates/node-ds.yaml
  src/test/csi-qingcloud/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S

#103 csi-neonsna v1.2.0
  src/test/csi-neonsan/Chart.yaml
  src/test/csi-neonsan/README.md
  src/test/csi-neonsan/values.yaml
Labels: approved, dco-signoff: yes, lgtm, size/S
