Repository kubesphere/helm-charts, pull requests merged in 2020-05, with the labels that each got.

#46 Create OWNERS
  OWNERS
Labels: size/S

#50 helm charts of aws-csi
  src/test/aws-ebs-csi-driver/.helmignore
  src/test/aws-ebs-csi-driver/Chart.yaml
  src/test/aws-ebs-csi-driver/templates/NOTES.txt
  src/test/aws-ebs-csi-driver/templates/_helpers.tpl
  src/test/aws-ebs-csi-driver/templates/csidriver.yaml
  src/test/aws-ebs-csi-driver/templates/daemonset.yaml
  src/test/aws-ebs-csi-driver/templates/deployment.yaml
  src/test/aws-ebs-csi-driver/templates/rbac.yaml
  src/test/aws-ebs-csi-driver/templates/serviceaccount.yaml
  src/test/aws-ebs-csi-driver/templates/statefulset.yaml
  src/test/aws-ebs-csi-driver/values.yaml
  src/test/aws-efs-csi-driver/Chart.yaml
  src/test/aws-efs-csi-driver/templates/NOTES.txt
  src/test/aws-efs-csi-driver/templates/_helpers.tpl
  src/test/aws-efs-csi-driver/templates/csidriver.yaml
  src/test/aws-efs-csi-driver/templates/daemonset.yaml
  src/test/aws-efs-csi-driver/values.yaml
  src/test/aws-fsx-csi-driver/.helmignore
  src/test/aws-fsx-csi-driver/Chart.yaml
  src/test/aws-fsx-csi-driver/README.md
  src/test/aws-fsx-csi-driver/templates/_helpers.tpl
  src/test/aws-fsx-csi-driver/templates/controller.yaml
  src/test/aws-fsx-csi-driver/templates/csidriver.yaml
  src/test/aws-fsx-csi-driver/templates/node.yaml
  src/test/aws-fsx-csi-driver/templates/serviceaccount.yaml
  src/test/aws-fsx-csi-driver/values.yaml
Labels: approved, lgtm, size/XXL

#49 helm charts of csi-neonsan
  src/test/csi-neonsan/.helmignore
  src/test/csi-neonsan/Chart.yaml
  src/test/csi-neonsan/README.md
  src/test/csi-neonsan/templates/controller-deploy.yaml
  src/test/csi-neonsan/templates/controller-rbac.yaml
  src/test/csi-neonsan/templates/csi-driver.yaml
  src/test/csi-neonsan/templates/node-ds.yaml
  src/test/csi-neonsan/templates/node-rbac.yaml
  src/test/csi-neonsan/values.yaml
Labels: approved, lgtm, size/XL
