Repository kubesphere/helm-charts, pull requests merged in 2020-06, with the labels that each got.

#51 update readme
  readme.md
  src/main/readme.md
  src/test/readme.md
Labels: approved, size/S

#52 sync harbor chart 1.4.0
  src/main/harbor/.helmignore
  src/main/harbor/.travis.yml
  src/main/harbor/Chart.yaml
  src/main/harbor/README.md
  src/main/harbor/docs/High Availability.md
  src/main/harbor/templates/NOTES.txt
  src/main/harbor/templates/_helpers.tpl
  src/main/harbor/templates/chartmuseum/chartmuseum-cm.yaml
  src/main/harbor/templates/chartmuseum/chartmuseum-dpl.yaml
  src/main/harbor/templates/chartmuseum/chartmuseum-svc.yaml
  src/main/harbor/templates/chartmuseum/chartmuseum-tls.yaml
  src/main/harbor/templates/clair/clair-dpl.yaml
  src/main/harbor/templates/clair/clair-secret.yaml
  src/main/harbor/templates/clair/clair-svc.yaml
  src/main/harbor/templates/clair/clair-tls.yaml
  src/main/harbor/templates/core/core-cm.yaml
  src/main/harbor/templates/core/core-dpl.yaml
  src/main/harbor/templates/core/core-secret.yaml
  src/main/harbor/templates/core/core-svc.yaml
  src/main/harbor/templates/core/core-tls.yaml
  src/main/harbor/templates/database/database-ss.yaml
  src/main/harbor/templates/ingress/ingress.yaml
  src/main/harbor/templates/internal/auto-tls.yaml
  src/main/harbor/templates/jobservice/jobservice-cm-env.yaml
  src/main/harbor/templates/jobservice/jobservice-cm.yaml
  src/main/harbor/templates/jobservice/jobservice-dpl.yaml
  src/main/harbor/templates/jobservice/jobservice-secrets.yaml
  src/main/harbor/templates/jobservice/jobservice-svc.yaml
  src/main/harbor/templates/jobservice/jobservice-tls.yaml
  src/main/harbor/templates/nginx/configmap-http.yaml
  src/main/harbor/templates/nginx/configmap-https.yaml
  src/main/harbor/templates/nginx/deployment.yaml
  src/main/harbor/templates/portal/comfigmap.yaml
  src/main/harbor/templates/portal/deployment.yaml
  src/main/harbor/templates/portal/service.yaml
  src/main/harbor/templates/portal/tls.yaml
  src/main/harbor/templates/registry/registry-cm.yaml
  src/main/harbor/templates/registry/registry-dpl.yaml
  src/main/harbor/templates/registry/registry-secret.yaml
  src/main/harbor/templates/registry/registry-svc.yaml
  src/main/harbor/templates/registry/registry-tls.yaml
  src/main/harbor/templates/trivy/trivy-secret.yaml
  src/main/harbor/templates/trivy/trivy-sts.yaml
  src/main/harbor/templates/trivy/trivy-svc.yaml
  src/main/harbor/templates/trivy/trivy-tls.yaml
  src/main/harbor/test/install_helm.sh
  src/main/harbor/test/verify.sh
  src/main/harbor/values.yaml
Labels: approved, size/XXL

#53 fork minio
  src/main/minio/.helmignore
  src/main/minio/Chart.yaml
  src/main/minio/OWNERS
  src/main/minio/README.md
  src/main/minio/ci/distributed-values.yaml
  src/main/minio/templates/NOTES.txt
  src/main/minio/templates/_helper_create_bucket.txt
  src/main/minio/templates/_helpers.tpl
  src/main/minio/templates/configmap.yaml
  src/main/minio/templates/deployment.yaml
  src/main/minio/templates/ingress.yaml
  src/main/minio/templates/networkpolicy.yaml
  src/main/minio/templates/poddisruptionbudget.yaml
  src/main/minio/templates/post-install-create-bucket-job.yaml
  src/main/minio/templates/post-install-prometheus-metrics-job.yaml
  src/main/minio/templates/post-install-prometheus-metrics-role.yaml
  src/main/minio/templates/post-install-prometheus-metrics-rolebinding.yaml
  src/main/minio/templates/post-install-prometheus-metrics-serviceaccount.yaml
  src/main/minio/templates/pvc.yaml
  src/main/minio/templates/secrets.yaml
  src/main/minio/templates/service.yaml
  src/main/minio/templates/serviceaccount.yaml
  src/main/minio/templates/servicemonitor.yaml
  src/main/minio/templates/statefulset.yaml
  src/main/minio/values.yaml
Labels: approved, do-not-merge/invalid-owners-file, size/XXL

#54 update helm chart of csi-neonsan
  src/test/csi-neonsan/Chart.yaml
  src/test/csi-neonsan/README.md
  src/test/csi-neonsan/values.yaml
Labels: approved, lgtm, size/S

#57 Remove pre-release versioning to align with Helm 3
  src/main/tomcat/Chart.yaml
  src/main/tomcat/templates/appsrv.yaml
  src/main/tomcat/values.yaml
Labels: approved, size/XS

#58 update local repo name
  index.html
  main/index.html
  test/index.html
Labels: size/XS
