Repository kubesphere/helm-charts, pull requests merged in 2021-09, with the labels that each got.

#171 update csi-driver apiVersion
  src/test/csi-neonsan/Chart.yaml
  src/test/csi-neonsan/templates/csi-driver.yaml
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/templates/qingcloud-driver.yaml
Labels: approved, lgtm, size/S

#172 Update csiDriver apiVersion to v1
  src/test/csi-neonsan/Chart.yaml
  src/test/csi-neonsan/templates/csi-driver.yaml
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/templates/qingcloud-driver.yaml
Labels: approved, lgtm, size/S

#173 Add stable repo
  src/stable/README.md
Labels: approved, size/S

#177 disable allowVolumeExpansion for nfs provisioner
  src/main/nfs-client-provisioner/Chart.yaml
  src/main/nfs-client-provisioner/README.md
  src/main/nfs-client-provisioner/values.yaml
Labels: approved, lgtm, size/XS

#176 Parameterize detach retry max time
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/templates/controller-deploy.yaml
  src/test/csi-qingcloud/values.yaml
Labels: approved, lgtm, size/XS
