Repository kubesphere/helm-charts, pull requests merged in 2021-08, with the labels that each got.

#158 Update csi-neonsan sidecar images
  src/test/csi-neonsan/Chart.yaml
  src/test/csi-neonsan/README.md
  src/test/csi-neonsan/templates/controller-deploy.yaml
  src/test/csi-neonsan/templates/controller-rbac.yaml
  src/test/csi-neonsan/values.yaml
Labels: lgtm, size/M

#161 Update reviewer
  OWNERS
Labels: size/S

#160 Enlarge resources and fix bugs
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/values.yaml
Labels: approved, lgtm, size/M

#163 Update build.sh
  build.sh
Labels: approved, size/XS

#162 delete duplicate enable-vts-status
  build.sh
  src/main/gitlab/Chart.yaml
  src/main/gitlab/charts/gitlab/charts/gitlab-shell/templates/nginx-tcp-configmap.yml
  src/main/gitlab/charts/nginx-ingress/.helmignore
  src/main/gitlab/charts/nginx-ingress/Chart.yaml
  src/main/gitlab/charts/nginx-ingress/index.md
  src/main/gitlab/charts/nginx-ingress/templates/NOTES.txt
  src/main/gitlab/charts/nginx-ingress/templates/_helpers.tpl
  src/main/gitlab/charts/nginx-ingress/templates/clusterrole.yaml
  src/main/gitlab/charts/nginx-ingress/templates/clusterrolebinding.yaml
  src/main/gitlab/charts/nginx-ingress/templates/controller-configmap.yaml
  src/main/gitlab/charts/nginx-ingress/templates/controller-daemonset.yaml
  src/main/gitlab/charts/nginx-ingress/templates/controller-deployment.yaml
  src/main/gitlab/charts/nginx-ingress/templates/controller-hpa.yaml
  src/main/gitlab/charts/nginx-ingress/templates/controller-metrics-service.yaml
  src/main/gitlab/charts/nginx-ingress/templates/controller-poddisruptionbudget.yaml
  src/main/gitlab/charts/nginx-ingress/templates/controller-service.yaml
  src/main/gitlab/charts/nginx-ingress/templates/controller-stats-service.yaml
  src/main/gitlab/charts/nginx-ingress/templates/default-backend-deployment.yaml
  src/main/gitlab/charts/nginx-ingress/templates/default-backend-poddisruptionbudget.yaml
  src/main/gitlab/charts/nginx-ingress/templates/default-backend-service.yaml
  src/main/gitlab/charts/nginx-ingress/templates/headers-configmap.yaml
  src/main/gitlab/charts/nginx-ingress/templates/podsecuritypolicy.yaml
  src/main/gitlab/charts/nginx-ingress/templates/role.yaml
  src/main/gitlab/charts/nginx-ingress/templates/rolebinding.yaml
  src/main/gitlab/charts/nginx-ingress/templates/serviceaccount.yaml
  src/main/gitlab/charts/nginx-ingress/templates/tcp-configmap.yaml
  src/main/gitlab/charts/nginx-ingress/templates/udp-configmap.yaml
  src/main/gitlab/charts/nginx-ingress/values.yaml
  src/main/gitlab/requirements.yaml
Labels: approved, lgtm, size/M

#166 add fluentbit-operator helm charts into repo
  src/main/fluentbit-operator/.helmignore
  src/main/fluentbit-operator/Chart.yaml
  src/main/fluentbit-operator/README.md
  src/main/fluentbit-operator/crds/logging.kubesphere.io_filter.yaml
  src/main/fluentbit-operator/crds/logging.kubesphere.io_fluentbit.yaml
  src/main/fluentbit-operator/crds/logging.kubesphere.io_fluentbitconfig.yaml
  src/main/fluentbit-operator/crds/logging.kubesphere.io_input.yaml
  src/main/fluentbit-operator/crds/logging.kubesphere.io_output.yaml
  src/main/fluentbit-operator/crds/logging.kubesphere.io_parser.yaml
  src/main/fluentbit-operator/templates/NOTES.txt
  src/main/fluentbit-operator/templates/_helpers.tpl
  src/main/fluentbit-operator/templates/filter-containerd.yaml
  src/main/fluentbit-operator/templates/filter-kubernetes.yaml
  src/main/fluentbit-operator/templates/filter-systemd.yaml
  src/main/fluentbit-operator/templates/fluentbit-containerd-config.yaml
  src/main/fluentbit-operator/templates/fluentbit-fluentBit.yaml
  src/main/fluentbit-operator/templates/fluentbit-operator-clusterRole.yaml
  src/main/fluentbit-operator/templates/fluentbit-operator-clusterRoleBinding.yaml
  src/main/fluentbit-operator/templates/fluentbit-operator-deployment.yaml
  src/main/fluentbit-operator/templates/fluentbitconfig-fluentBitConfig.yaml
  src/main/fluentbit-operator/templates/input-systemd-docker.yaml
  src/main/fluentbit-operator/templates/input-systemd-kubelet.yaml
  src/main/fluentbit-operator/templates/input-tail.yaml
  src/main/fluentbit-operator/templates/lua-config.yaml
  src/main/fluentbit-operator/templates/output-elasticsearch.yaml
  src/main/fluentbit-operator/templates/output-forward.yaml
  src/main/fluentbit-operator/templates/output-kafka.yaml
  src/main/fluentbit-operator/templates/serviceaccount.yaml
  src/main/fluentbit-operator/values.yaml
Labels: approved, lgtm, size/XXL

#167 Add new chart minio-gateway
  src/test/minio-gateway/.helmignore
  src/test/minio-gateway/Chart.lock
  src/test/minio-gateway/Chart.yaml
  src/test/minio-gateway/README.md
  src/test/minio-gateway/charts/common/.helmignore
  src/test/minio-gateway/charts/common/Chart.yaml
  src/test/minio-gateway/charts/common/README.md
  src/test/minio-gateway/charts/common/templates/_affinities.tpl
  src/test/minio-gateway/charts/common/templates/_capabilities.tpl
  src/test/minio-gateway/charts/common/templates/_errors.tpl
  src/test/minio-gateway/charts/common/templates/_images.tpl
  src/test/minio-gateway/charts/common/templates/_ingress.tpl
  src/test/minio-gateway/charts/common/templates/_labels.tpl
  src/test/minio-gateway/charts/common/templates/_names.tpl
  src/test/minio-gateway/charts/common/templates/_secrets.tpl
  src/test/minio-gateway/charts/common/templates/_storage.tpl
  src/test/minio-gateway/charts/common/templates/_tplvalues.tpl
  src/test/minio-gateway/charts/common/templates/_utils.tpl
  src/test/minio-gateway/charts/common/templates/_warnings.tpl
  src/test/minio-gateway/charts/common/templates/validations/_cassandra.tpl
  src/test/minio-gateway/charts/common/templates/validations/_mariadb.tpl
  src/test/minio-gateway/charts/common/templates/validations/_mongodb.tpl
  src/test/minio-gateway/charts/common/templates/validations/_postgresql.tpl
  src/test/minio-gateway/charts/common/templates/validations/_redis.tpl
  src/test/minio-gateway/charts/common/templates/validations/_validations.tpl
  src/test/minio-gateway/charts/common/values.yaml
  src/test/minio-gateway/ci/values-gateway.yaml
  src/test/minio-gateway/ci/values-production.yaml
  src/test/minio-gateway/example-minio-gateway-values.yaml
  src/test/minio-gateway/templates/NOTES.txt
  src/test/minio-gateway/templates/_helpers.tpl
  src/test/minio-gateway/templates/distributed/headless-svc.yaml
  src/test/minio-gateway/templates/distributed/pdb.yaml
  src/test/minio-gateway/templates/distributed/statefulset.yaml
  src/test/minio-gateway/templates/extra-list.yaml
  src/test/minio-gateway/templates/gateway/deployment.yaml
  src/test/minio-gateway/templates/ingress.yaml
  src/test/minio-gateway/templates/networkpolicy.yaml
  src/test/minio-gateway/templates/pvc.yaml
  src/test/minio-gateway/templates/secrets.yaml
  src/test/minio-gateway/templates/service.yaml
  src/test/minio-gateway/templates/serviceaccount.yaml
  src/test/minio-gateway/templates/servicemonitor.yaml
  src/test/minio-gateway/templates/standalone/deployment.yaml
  src/test/minio-gateway/templates/tls-secrets.yaml
  src/test/minio-gateway/values.yaml
Labels: approved, lgtm, size/XXL

#170 Fix travis error
  src/test/minio-gateway/Chart.lock
Labels: approved, size/XS
