Repository kubesphere/helm-charts, pull requests merged in 2021-11, with the labels that each got.

#186 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/S

#187 [stable/nocalhost] update nocalhost chart version to 0.6.4
  src/stable/nocalhost/Chart.yaml
  src/stable/nocalhost/values.yaml
Labels: approved, lgtm, size/XS

#188 add VPA yaml and CHANGELOG.
  src/test/csi-qingcloud/CHANGELOG/CHANGELOG-1.3.md
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/README.md
  src/test/csi-qingcloud/templates/vpa.yaml
  src/test/csi-qingcloud/values.yaml
Labels: approved, lgtm, size/L

#182 add juicefs chart
  src/stable/juicefs/.helmignore
  src/stable/juicefs/Chart.yaml
  src/stable/juicefs/README.md
  src/stable/juicefs/templates/NOTES.txt
  src/stable/juicefs/templates/_helpers.tpl
  src/stable/juicefs/templates/controller.yaml
  src/stable/juicefs/templates/csidriver.yaml
  src/stable/juicefs/templates/daemonset.yaml
  src/stable/juicefs/templates/serviceaccount.yaml
  src/stable/juicefs/templates/storageclass.yaml
  src/stable/juicefs/values.yaml
Labels: approved, lgtm, size/XL

#189 feat: add apisix
  src/main/apisix-dashboard/.helmignore
  src/main/apisix-dashboard/Chart.yaml
  src/main/apisix-dashboard/charts/.gitkeep
  src/main/apisix-dashboard/templates/NOTES.txt
  src/main/apisix-dashboard/templates/_helpers.tpl
  src/main/apisix-dashboard/templates/configmap.yaml
  src/main/apisix-dashboard/templates/deployment.yaml
  src/main/apisix-dashboard/templates/hpa.yaml
  src/main/apisix-dashboard/templates/ingress.yaml
  src/main/apisix-dashboard/templates/service.yaml
  src/main/apisix-dashboard/templates/serviceaccount.yaml
  src/main/apisix-dashboard/templates/tests/test-connection.yaml
  src/main/apisix-dashboard/values.yaml
  src/main/apisix-ingress-controller/.helmignore
  src/main/apisix-ingress-controller/Chart.yaml
  src/main/apisix-ingress-controller/README.md
  src/main/apisix-ingress-controller/charts/.gitkeep
  src/main/apisix-ingress-controller/crds/customresourcedefinitions.yaml
  src/main/apisix-ingress-controller/templates/NOTES.txt
  src/main/apisix-ingress-controller/templates/_helpers.tpl
  src/main/apisix-ingress-controller/templates/configmap.yaml
  src/main/apisix-ingress-controller/templates/deployment.yaml
  src/main/apisix-ingress-controller/templates/hpa.yaml
  src/main/apisix-ingress-controller/templates/rbac.yaml
  src/main/apisix-ingress-controller/templates/service-account.yaml
  src/main/apisix-ingress-controller/templates/service.yaml
  src/main/apisix-ingress-controller/templates/servicemonitor.yaml
  src/main/apisix-ingress-controller/values.yaml
  src/main/apisix/.helmignore
  src/main/apisix/Chart.lock
  src/main/apisix/Chart.yaml
  src/main/apisix/README.md
  src/main/apisix/charts/apisix-dashboard-0.3.0.tgz
  src/main/apisix/charts/apisix-ingress-controller-0.8.0.tgz
  src/main/apisix/charts/etcd-6.2.6.tgz
  src/main/apisix/templates/NOTES.txt
  src/main/apisix/templates/_helpers.tpl
  src/main/apisix/templates/configmap.yaml
  src/main/apisix/templates/deployment.yaml
  src/main/apisix/templates/hpa.yaml
  src/main/apisix/templates/ingress.yaml
  src/main/apisix/templates/service-admin.yaml
  src/main/apisix/templates/service-gateway.yaml
  src/main/apisix/values.yaml
Labels: approved, lgtm, size/XXL

#196 Add InAccel FPGA Operator
  src/stable/fpga-operator/Chart.lock
  src/stable/fpga-operator/Chart.yaml
  src/stable/fpga-operator/README.md
  src/stable/fpga-operator/charts/node-feature-discovery/.helmignore
  src/stable/fpga-operator/charts/node-feature-discovery/Chart.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/README.md
  src/stable/fpga-operator/charts/node-feature-discovery/templates/_helpers.tpl
  src/stable/fpga-operator/charts/node-feature-discovery/templates/clusterrole.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/clusterrolebinding.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/master.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/nfd-worker-conf.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/service.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/serviceaccount.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/worker.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/values.yaml
  src/stable/fpga-operator/templates/NOTES.txt
  src/stable/fpga-operator/templates/_helpers.tpl
  src/stable/fpga-operator/templates/cluster-role-binding.yaml
  src/stable/fpga-operator/templates/cluster-role.yaml
  src/stable/fpga-operator/templates/csi-driver.yaml
  src/stable/fpga-operator/templates/daemon-set.yaml
  src/stable/fpga-operator/templates/deployment.yaml
  src/stable/fpga-operator/templates/mutating-webhook-configuration.yaml
  src/stable/fpga-operator/templates/secret.yaml
  src/stable/fpga-operator/templates/service-account.yaml
  src/stable/fpga-operator/templates/service.yaml
  src/stable/fpga-operator/values.yaml
Labels: approved, area/app-management, lgtm, size/XXL

#195 delete useless value
  src/stable/juicefs/Chart.yaml
  src/stable/juicefs/README.md
  src/stable/juicefs/values.yaml
Labels: approved, lgtm, size/S

#191 Upgrade ks-installer chart to v3.2.0
  src/main/ks-installer/Chart.yaml
  src/main/ks-installer/README.md
  src/main/ks-installer/templates/NOTES.txt
  src/main/ks-installer/templates/clusterconfiguration.yaml
  src/main/ks-installer/values.yaml
  src/test/ks-installer/Chart.yaml
  src/test/ks-installer/README.md
  src/test/ks-installer/templates/NOTES.txt
  src/test/ks-installer/templates/clusterconfiguration.yaml
  src/test/ks-installer/values.yaml
Labels: approved, lgtm, size/XXL

#192 Fix node-ds.yaml kubeletDir
  src/test/csi-qingcloud/Chart.yaml
  src/test/csi-qingcloud/templates/node-ds.yaml
Labels: approved, lgtm, size/S
