Repository kubesphere/helm-charts, pull requests merged in 2021-12, with the labels that each got.

#194 upgrade Chaos Mesh to v2.0.4
  src/stable/chaos-mesh/Chart.yaml
  src/stable/chaos-mesh/templates/secrets-configuration.yaml
  src/stable/chaos-mesh/values.yaml
Labels: approved, lgtm, size/M

#197 upgrade default sonarqube version to lts 8.9-community
  src/main/sonarqube/Chart.yaml
  src/main/sonarqube/README.md
  src/main/sonarqube/values.yaml
Labels: approved, lgtm, size/XS

#200 change rbac apiVersion
  src/main/elasticsearch-exporter/Chart.yaml
  src/main/elasticsearch-exporter/templates/role.yaml
  src/main/elasticsearch-exporter/templates/rolebinding.yaml
  src/main/gitlab/doc/installation/tools.md
  src/main/redis-exporter/Chart.yaml
  src/main/redis-exporter/templates/role.yaml
  src/main/redis-exporter/templates/rolebinding.yaml
Labels: approved, lgtm, size/S

#202 quote redis password
  src/main/redis-exporter/Chart.yaml
  src/main/redis-exporter/templates/deployment.yaml
Labels: approved, lgtm, size/XS

#203 add github action
  .github/workflows/build-chart-index.yaml
  build.sh
Labels: approved, lgtm, size/M

#201 [stable/nocalhost] update version to 0.6.9
  src/stable/nocalhost/Chart.yaml
  src/stable/nocalhost/values.yaml
Labels: approved, lgtm, size/XS

#205 Upload pvc-autoresizer
  src/main/pvc-autoresizer/Chart.yaml
  src/main/pvc-autoresizer/README.md
  src/main/pvc-autoresizer/templates/_helpers.tpl
  src/main/pvc-autoresizer/templates/controller/clusterrole.yaml
  src/main/pvc-autoresizer/templates/controller/clusterrolebinding.yaml
  src/main/pvc-autoresizer/templates/controller/deployment.yaml
  src/main/pvc-autoresizer/templates/controller/role.yaml
  src/main/pvc-autoresizer/templates/controller/rolebinding.yaml
  src/main/pvc-autoresizer/templates/controller/serviceaccount.yaml
  src/main/pvc-autoresizer/values.yaml
Labels: approved, lgtm, size/L

#209 Upload storageclass-accessor
  src/main/storageclass-accessor/Chart.yaml
  src/main/storageclass-accessor/README.md
  src/main/storageclass-accessor/templates/accessor.yaml
  src/main/storageclass-accessor/templates/deployment.yaml
  src/main/storageclass-accessor/templates/rbac.yaml
  src/main/storageclass-accessor/templates/service.yaml
  src/main/storageclass-accessor/templates/validatingwebhook.yaml
  src/main/storageclass-accessor/values.yaml
Labels: approved, lgtm, size/L
