Repository kubesphere/helm-charts, pull requests merged in 2022-03, with the labels that each got.

#219 feat: add ys1000 v2.2.2 to ks app store
  src/stable/ys1000/Chart.yaml
  src/stable/ys1000/README.md
  src/stable/ys1000/crds/crds.yaml
  src/stable/ys1000/templates/NOTES.txt
  src/stable/ys1000/templates/_helpers.tpl
  src/stable/ys1000/templates/cluster-role-bindings.yaml
  src/stable/ys1000/templates/cluster-roles.yaml
  src/stable/ys1000/templates/hpa.yaml
  src/stable/ys1000/templates/ingress.yaml
  src/stable/ys1000/templates/local-cluster.yaml
  src/stable/ys1000/templates/migconfig.yaml
  src/stable/ys1000/templates/migstorage.yaml
  src/stable/ys1000/templates/operator-deployment.yaml
  src/stable/ys1000/templates/role-bindings.yaml
  src/stable/ys1000/templates/roles.yaml
  src/stable/ys1000/templates/s3-configmap.yaml
  src/stable/ys1000/templates/s3-secret.yaml
  src/stable/ys1000/templates/serviceaccount.yaml
  src/stable/ys1000/templates/tests/test-connection.yaml
  src/stable/ys1000/values.yaml
Labels: approved, lgtm, size/XXL

#218 Recommanded Kubernetes and Helm labels
  src/main/elasticsearch-exporter/Chart.yaml
  src/main/elasticsearch-exporter/templates/_helpers.tpl
  src/main/elasticsearch-exporter/templates/cert-secret.yaml
  src/main/elasticsearch-exporter/templates/deployment.yaml
  src/main/elasticsearch-exporter/templates/podsecuritypolicies.yaml
  src/main/elasticsearch-exporter/templates/prometheusrule.yaml
  src/main/elasticsearch-exporter/templates/role.yaml
  src/main/elasticsearch-exporter/templates/rolebinding.yaml
  src/main/elasticsearch-exporter/templates/service.yaml
  src/main/elasticsearch-exporter/templates/serviceaccount.yaml
  src/main/elasticsearch-exporter/templates/servicemonitor.yaml
  src/main/elasticsearch-exporter/values.yaml
Labels: approved, lgtm, size/M

#223 change the name of JH helm charts.
  src/stable/jh/Chart.yaml
Labels: approved, lgtm, size/XS

#224 rm chart gitlab
  stable/gitlab-5.8.2.tgz
  stable/index.yaml
Labels: size/M
