Repository kubesphere/helm-charts, pull requests merged in 2022-08, with the labels that each got.

#252 Add DeepFlow
  build.sh
  src/depends/Chart.lock
  src/depends/Chart.yaml
Labels: approved, lgtm, size/S

#254 update deepflow chart
  src/depends/Chart.lock
  src/depends/Chart.yaml
Labels: approved, lgtm, size/S

#256 update deepflow helm chart
  src/depends/Chart.lock
  src/depends/Chart.yaml
Labels: approved, lgtm, size/XS

#253 release juicefs 1.0.0
  src/stable/juicefs/Chart.yaml
  src/stable/juicefs/README.md
  src/stable/juicefs/templates/storageclass.yaml
  src/stable/juicefs/values.yaml
Labels: approved, lgtm, size/M

#258 Bump crane from 0.5.1 to 0.5.2 in /src/stable/crane
  src/stable/crane/Chart.yaml
  src/stable/crane/crds/autoscaling.crane.io_effectiveverticalpodautoscalers.yaml
Labels: approved, lgtm, size/XL
