Repository kubesphere/helm-charts, pull requests merged in 2022-10, with the labels that each got.

#267 update app version for qingcloud csi
  src/test/csi-qingcloud/Chart.yaml
Labels: size/XS

#265 add issues build
  .github/workflows/issues-build-latest-chart.yaml
  build.sh
  src/depends/Chart.lock
  src/latest/Chart.yaml
Labels: size/M

#271 1.release csi-neonsan helm chart；
  src/test/csi-neonsan/Chart.yaml
  src/test/csi-neonsan/templates/controller-deploy.yaml
  src/test/csi-neonsan/templates/node-ds.yaml
  src/test/csi-neonsan/values.yaml
Labels: approved, lgtm, size/S

#268 add curvefs-csi chart
  src/test/curvefs-csi/.helmignore
  src/test/curvefs-csi/Chart.yaml
  src/test/curvefs-csi/README.md
  src/test/curvefs-csi/templates/_helpers.tpl
  src/test/curvefs-csi/templates/controller.yaml
  src/test/curvefs-csi/templates/driver.yaml
  src/test/curvefs-csi/templates/node.yaml
  src/test/curvefs-csi/templates/rbac.yaml
  src/test/curvefs-csi/templates/storageclass.yaml
  src/test/curvefs-csi/values.yaml
Labels: approved, lgtm, size/L
