Repository kubesphere/helm-charts, pull requests merged in 2022-02, with the labels that each got.

#212 Upgrade InAccel FPGA Operator
  src/stable/fpga-operator/Chart.lock
  src/stable/fpga-operator/Chart.yaml
  src/stable/fpga-operator/README.md
  src/stable/fpga-operator/charts/node-feature-discovery/Chart.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/README.md
  src/stable/fpga-operator/charts/node-feature-discovery/manifests/nodefeaturerule-crd.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/_helpers.tpl
  src/stable/fpga-operator/charts/node-feature-discovery/templates/cert-manager-certs.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/cert-manager-issuer.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/clusterrole.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/clusterrolebinding.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/master.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/nfd-worker-conf.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/nodefeaturerule-crd.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/serviceaccount.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/topologyupdater-crds.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/topologyupdater.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/templates/worker.yaml
  src/stable/fpga-operator/charts/node-feature-discovery/values.yaml
  src/stable/fpga-operator/templates/NOTES.txt
  src/stable/fpga-operator/templates/_helpers.tpl
  src/stable/fpga-operator/templates/cluster-role-binding.yaml
  src/stable/fpga-operator/templates/cluster-role.yaml
  src/stable/fpga-operator/templates/csi-driver.yaml
  src/stable/fpga-operator/templates/daemon-set.yaml
  src/stable/fpga-operator/templates/deployment.yaml
  src/stable/fpga-operator/templates/mutating-webhook-configuration.yaml
  src/stable/fpga-operator/templates/secret.yaml
  src/stable/fpga-operator/templates/service-account.yaml
  src/stable/fpga-operator/templates/service.yaml
  src/stable/fpga-operator/templates/tests/vadd.yaml
  src/stable/fpga-operator/values.schema.json
  src/stable/fpga-operator/values.yaml
Labels: approved, lgtm, size/XXL

#213 upgrade openELB version
  src/test/porter/Chart.yaml
  src/test/porter/templates/_helper.tpl
  src/test/porter/templates/admission-webhooks/job-patch/clusterrole.yaml
  src/test/porter/templates/admission-webhooks/job-patch/job-patchWebhook.yaml
  src/test/porter/templates/admission-webhooks/mutating-webhook.yaml
  src/test/porter/values.yaml
Labels: approved, lgtm, size/M

#214 add radondb maintainers
  src/test/radondb-clickhouse/Chart.yaml
  src/test/radondb-mysql/Chart.yaml
  src/test/radondb-postgresql/Chart.yaml
  src/test/radondb-postgresql/charts/common/Chart.yaml
Labels: approved, lgtm, size/M

#217 update openelb version
  src/test/openelb/Chart.yaml
  src/test/openelb/values.yaml
Labels: approved, lgtm, size/XS

#206 Introduce Easegress to stable part in kubesphere
  src/stable/easegress/.helmignore
  src/stable/easegress/Chart.yaml
  src/stable/easegress/README.md
  src/stable/easegress/templates/ClusterRole.yaml
  src/stable/easegress/templates/ClusterRoleBinding.yaml
  src/stable/easegress/templates/ConfigMap.yaml
  src/stable/easegress/templates/Deployment.yaml
  src/stable/easegress/templates/PersistentVolume.yaml
  src/stable/easegress/templates/Service.yaml
  src/stable/easegress/templates/ServiceAccount.yaml
  src/stable/easegress/templates/StatefulSet.yaml
  src/stable/easegress/values.yaml
Labels: approved, lgtm, size/L
