Repository kubesphere/helm-charts, pull requests merged in 2022-11, with the labels that each got.

#276 Change radondb mysql & pg name and icon
  src/test/radondb-mysql/Chart.yaml
  src/test/radondb-postgresql/Chart.yaml
Labels: approved, lgtm, size/S

#277 move curvefs-csi from test to stable
  src/stable/curvefs-csi/.helmignore
  src/stable/curvefs-csi/Chart.yaml
  src/stable/curvefs-csi/README.md
  src/stable/curvefs-csi/templates/_helpers.tpl
  src/stable/curvefs-csi/templates/controller.yaml
  src/stable/curvefs-csi/templates/driver.yaml
  src/stable/curvefs-csi/templates/node.yaml
  src/stable/curvefs-csi/templates/rbac.yaml
  src/stable/curvefs-csi/templates/storageclass.yaml
  src/stable/curvefs-csi/values.yaml
Labels: approved, lgtm, size/XS

#278 Update crds
  src/test/ks-core/crds/kubesphere.io_extensions.yaml
  src/test/ks-core/crds/kubesphere.io_extensionversions.yaml
  src/test/ks-core/crds/kubesphere.io_subscriptions.yaml
Labels: approved, lgtm, size/L
