Repository kubesphere/helm-charts, pull requests merged in 2022-01, with the labels that each got.

#210 update sotrageclass-accessor apiversion to v2
  src/main/storageclass-accessor/Chart.yaml
Labels: approved, lgtm, size/XS

#211 commit to gh-pages when merging to master
  .github/workflows/build-chart-index.yaml
Labels: approved, size/XS

#208 upload edgemesh helm chart
  src/stable/edgemesh/.helmignore
  src/stable/edgemesh/Chart.yaml
  src/stable/edgemesh/README.md
  src/stable/edgemesh/charts/agent/.helmignore
  src/stable/edgemesh/charts/agent/Chart.yaml
  src/stable/edgemesh/charts/agent/templates/01-serviceaccount.yaml
  src/stable/edgemesh/charts/agent/templates/02-clusterrole.yaml
  src/stable/edgemesh/charts/agent/templates/03-clusterrolebinding.yaml
  src/stable/edgemesh/charts/agent/templates/04-configmap.yaml
  src/stable/edgemesh/charts/agent/templates/05-daemonset.yaml
  src/stable/edgemesh/charts/agent/values.yaml
  src/stable/edgemesh/charts/server/.helmignore
  src/stable/edgemesh/charts/server/Chart.yaml
  src/stable/edgemesh/charts/server/templates/01-serviceaccount.yaml
  src/stable/edgemesh/charts/server/templates/02-clusterrole.yaml
  src/stable/edgemesh/charts/server/templates/03-clusterrolebinding.yaml
  src/stable/edgemesh/charts/server/templates/04-configmap.yaml
  src/stable/edgemesh/charts/server/templates/05-deployment.yaml
  src/stable/edgemesh/charts/server/values.yaml
  src/stable/edgemesh/crds/istio/crd-destinationrule.yaml
  src/stable/edgemesh/crds/istio/crd-gateway.yaml
  src/stable/edgemesh/crds/istio/crd-virtualservice.yaml
  src/stable/edgemesh/templates/NOTES.txt
  src/stable/edgemesh/values.yaml
Labels: approved, lgtm, size/XXL

#207 Upgrade ks-installer to 3.2.1
  src/main/ks-installer/Chart.yaml
  src/main/ks-installer/README.md
  src/main/ks-installer/values.yaml
  src/test/ks-installer/Chart.yaml
  src/test/ks-installer/README.md
  src/test/ks-installer/values.yaml
Labels: approved, lgtm, size/S
