Repository kubesphere/helm-charts, pull requests merged in 2024-09, with the labels that each got.

#405 Bump ks-core from 0.4.0 to 1.1.0 in /src/main/ks-core
  src/main/ks-core/crds/appstore.kubesphere.io_applicationclasses.yaml
  src/main/ks-core/crds/appstore.kubesphere.io_applicationresources.yaml
  src/main/ks-core/crds/appstore.kubesphere.io_applications.yaml
  src/main/ks-core/crds/auditing.kubesphere.io_rules.yaml
  src/main/ks-core/crds/auditing.kubesphere.io_webhooks.yaml
  src/main/ks-core/crds/cluster.kubesphere.io_clusters.yaml
  src/main/ks-core/crds/extensions.kubesphere.io_apiservices.yaml
  src/main/ks-core/crds/extensions.kubesphere.io_jsbundles.yaml
  src/main/ks-core/crds/extensions.kubesphere.io_reverseproxies.yaml
  src/main/ks-core/crds/gateway.kubesphere.io_ingressclassscopes.yaml
  src/main/ks-core/crds/iam.kubesphere.io_builtinroles.yaml
  src/main/ks-core/crds/iam.kubesphere.io_categories.yaml
  src/main/ks-core/crds/iam.kubesphere.io_clusterrolebindings.yaml
  src/main/ks-core/crds/iam.kubesphere.io_clusterroles.yaml
  src/main/ks-core/crds/iam.kubesphere.io_globalrolebindings.yaml
  src/main/ks-core/crds/iam.kubesphere.io_globalroles.yaml
  src/main/ks-core/crds/iam.kubesphere.io_groupbindings.yaml
  src/main/ks-core/crds/iam.kubesphere.io_groups.yaml
  src/main/ks-core/crds/iam.kubesphere.io_loginrecords.yaml
  src/main/ks-core/crds/iam.kubesphere.io_rolebindings.yaml
  src/main/ks-core/crds/iam.kubesphere.io_roles.yaml
  src/main/ks-core/crds/iam.kubesphere.io_roletemplates.yaml
  src/main/ks-core/crds/iam.kubesphere.io_users.yaml
  src/main/ks-core/crds/iam.kubesphere.io_workspacerolebindings.yaml
  src/main/ks-core/crds/iam.kubesphere.io_workspaceroles.yaml
  src/main/ks-core/crds/kubesphere.io_categories.yaml
  src/main/ks-core/crds/kubesphere.io_extensions.yaml
  src/main/ks-core/crds/kubesphere.io_extensionversions.yaml
  src/main/ks-core/crds/kubesphere.io_installplans.yaml
  src/main/ks-core/crds/kubesphere.io_repositories.yaml
  src/main/ks-core/crds/kubesphere.io_serviceaccounts.yaml
  src/main/ks-core/crds/marketplace.kubesphere.io_subscriptions.yaml
  src/main/ks-core/crds/oauth.kubesphere.io_oauthclients.yaml
  src/main/ks-core/crds/quota.kubesphere.io_resourcequotas.yaml
  src/main/ks-core/crds/storage.kubesphere.io_provisionercapabilities.yaml
  src/main/ks-core/crds/storage.kubesphere.io_storageclasscapabilities.yaml
  src/main/ks-core/crds/telemetry.kubesphere.io_clusterinfoes.yaml
  src/main/ks-core/crds/tenant.kubesphere.io_workspaces.yaml
  src/main/ks-core/crds/tenant.kubesphere.io_workspacetemplates.yaml
  src/main/ks-core/templates/categories.yaml
  src/main/ks-core/templates/globalrolebingings.yaml
  src/main/ks-core/templates/ks-agent.yml
  src/main/ks-core/templates/ks-apiserver.yml
  src/main/ks-core/templates/ks-console-config.yml
  src/main/ks-core/templates/ks-console.yml
  src/main/ks-core/templates/marketplace-config.yaml
  src/main/ks-core/templates/post-install-job.yaml
  src/main/ks-core/templates/pre-delete-job.yaml
  src/main/ks-core/templates/services.yml
Labels: approved

#412 Update src/main/ks-core
  src/main/ks-core/templates/kubesphere-config.yaml
  src/main/ks-core/values.yaml
Labels: approved, lgtm, size/S

#413 Replace main/ks-core-1.1.0.tgz
  main/ks-core-1.1.0.tgz
Labels: size/XS

#416 Temporary removal of deepflow
  src/latest/Chart.yaml
Labels: approved, size/XS

#417 Update ks-core version to v1.1.1
  src/main/ks-core/Chart.yaml
  src/main/ks-core/templates/_images.tpl
  src/main/ks-core/templates/extension-museum.yaml
  src/main/ks-core/values.yaml
Labels: approved, size/M
