Repository kubesphere/helm-charts, pull requests merged in 2024-01, with the labels that each got.

#318 fix ks-installer NOTES typo
  src/main/ks-installer/templates/NOTES.txt
Labels: approved, lgtm, size/XS

#347 Upgrade databend to v1.2.279
  src/stable/databend-meta/Chart.yaml
  src/stable/databend-meta/README.md
  src/stable/databend-meta/templates/poddisruptionbudget.yaml
  src/stable/databend-meta/templates/statefulset.yaml
  src/stable/databend-meta/values.yaml
  src/stable/databend-query/Chart.yaml
  src/stable/databend-query/README.md
  src/stable/databend-query/charts/common-1.17.1.tgz
  src/stable/databend-query/templates/configmap.yaml
  src/stable/databend-query/templates/pvc.yaml
  src/stable/databend-query/templates/service.yaml
  src/stable/databend-query/templates/statefulset.yaml
  src/stable/databend-query/values.yaml
Labels: approved, lgtm, size/L

#353 upgrade helm version to 3.14.0
  build.sh
Labels: approved, size/XS
